### PR TITLE
README.md: Add Rust port of Radamsa

### PR DESCRIPTION
**Pull request by Nicceboy**
Include Microsoft Rust port of Radamsa general purpose fuzzer

### CODE REVIEW

**Comment by Shnatsel** [comment]
Thank you for the addition!

Do I understand correctly that it is not coverage-guided, unlike afl/libfuzzer/honggfuzz? If so it is something I'd like to note in the table.

**Comment by Nicceboy** [comment]
It is not coverage guided by itself, but you can use it with libfuzzer for example to get the coverage : https://llvm.org/docs/LibFuzzer.html#fuzz-target 

The mutator is also integrated to Afl++ for example https://aflplus.plus/features/

This fuzzer is known for its very good mutation capabilities.

**Comment by Shnatsel** [comment]
Thank you for the clarification! Just to confirm, can it fuzz Rust code?

**Comment by Nicceboy** [comment]
The rusty-radamsa port can be used as library in your Rust code, but in general the CLI version can fuzz anything.

```rust
use std::boxed::Box;
extern crate rusty_radamsa;
let data = Box::<[u8]>::from("Hello World 12345689\n".as_bytes());
let mut out_buffer = Box::<[u8]>::from(vec![0u8; 2048]);
let max_len = out_buffer.len(); //aka truncate
let seed: u64 = 42;
let _len = rusty_radamsa::radamsa(&data, data.len(), &mut out_buffer, max_len, seed);
```

**Comment by Shnatsel** [comment]
Merged, thanks!

I've updated the description in the main branch, does that look descriptive?

**Comment by Nicceboy** [comment]
I think it is OK!

**Pull request merged**
